OPENAI_API_KEY = "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"
APP_PIN = "2013+1978"  # Or whatever PIN you give Mohamad
